# Generated by Django 5.0.6 on 2024-05-19 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_birth_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='postalـcode',
            new_name='postal_code',
        ),
    ]
