# Generated by Django 5.0.6 on 2024-05-19 13:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_postalـcode_userprofile_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
